apiVersion: v1
kind: Pod
metadata:
  name: my-app
spec:
  nodeName: worker-0.xxxx-36f4.redhat.com
  containers:
  - name: app
    image: centos
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: my-claim
