apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ibm-powervc-csi-volume-default
  resources:
    requests:
      storage: 1Gi
