apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ibm-powervc-csi-volume-default
  csi:
    driver: ibm-powervc-csi-driver
    volumeHandle: e0c79e94-0ce3-434b-9884-dde38433176b
